import baseConfig from '@flavohub/config/eslint-base';

export default [
  ...baseConfig,
  {
    // next-env.d.ts is generated by Next.js and uses triple-slash references that
    // the typescript-eslint rule would flag. Exclude it from linting entirely.
    ignores: ['**/next-env.d.ts'],
  },
  {
    // NestJS emitDecoratorMetadata requires injected constructor deps to be value
    // imports. consistent-type-imports would erase the runtime token and break DI.
    files: ['apps/api/src/**/*.ts'],
    rules: {
      '@typescript-eslint/consistent-type-imports': 'off',
    },
  },
];
